### ISSUE TITLE
mod name mismatch

### ISSUE THREAD

**Issue by ronamit** [agc93/vortex-showcase#11]
If I  install several mod files from the same nexus page (e.g, "Hearthfire Extended")
then in Vortex, I will see "Hearthfire Extended", "Hearthfire Extended - CFTO Patch", "Hearthfire Extended - Cutting Room Floor Patch" etc.,
but in the Modwat list, I see only "Hearthfire Extended" repeated several times.

Can the mod naming in Modwat be as in Vortex?

BTW, the new sort option works great. thanks again

**Comment by agc93** [comment]
I'll see if I can tweak which attribute we use. This happens because internally (confusingly) Vortex has about 4 different names for any given mod. I'll try and find a more unique one to use

**Comment by ronamit** [comment]
the issue seems solved in the new version, thanks!

**Comment by agc93** [comment]
Awesome! I wasn't 100% sure that would fix things so thanks for confirming 👍
