### ISSUE TITLE
Missing plugins

### ISSUE THREAD

**Issue by ronamit** [agc93/vortex-showcase#12]
Vortex 1.3.17
Showcase extension version 0.1.6

Some of the plugins are missing from my showcase: https://modwat.ch/u/RON4A1/plugins

For comparison here is the load order from Vortex:
[loadorder.txt](https://github.com/agc93/vortex-showcase/files/5500493/loadorder.txt)

The mod list is fine though.

**Comment by agc93** [comment]
Are any of your plugins manually installed? Showcase will only include plugins that came from Vortex-managed mods, while the Plugins screen (and loadorder.txt) will just include any mods in your game folder if I remember correctly.

**Comment by agc93** [comment]
Additional question: can you open your Plugins tab in Vortex and check if the following plugins appear as Enabled or Disabled in Vortex?

- `point the way.esp`
- `tkrecoil.esp`
- `hitstop.esp`

I just need to know what the row in Plugins *says* in Vortex to narrow this behaviour down

**Comment by ronamit** [comment]
All 3 plugins are disabled (since  they included in a merge)

Thank you for addressing the issue :)

**Comment by agc93** [comment]
Thanks for the fast response! In that case, this is pretty much expected behaviour. Plugins will only be included in the showcase (that gets sent to Modwat.ch) if they're *enabled*. 

> The `loadorder.txt` is only used by mod managers and isn't representative of what the game is going to load.

**Comment by ronamit** [comment]
this explains the mismatch with the indexing in Vortex load order....
Thanks!
