### ISSUE TITLE
deploy order column

### ISSUE THREAD

**Issue by ronamit** [agc93/vortex-showcase#8]
Hi agc93, Thanks for your great work!
I am using Vortex Show - Extended Formats to create a csv file.
It would be great if it could include a deploy order column,
or add an option to create a showcase sorted by load order

**Comment by agc93** [comment]
Thanks for the suggestion @ronamit ! I'll look into this and _should_ be able to at least add the deployment order to the output.

**Comment by agc93** [comment]
I've just published v0.1.4 which adds a new setting (in Settings > Interface) to control the sort order for all showcases. This includes the ability to sort by deploy order.

It will take a couple of days for it to be available (Nexus Mods have to manually approve every update :| ) then you should be able to sort your exported mod list by deployment order.

**Comment by ronamit** [comment]
perfect :)
Thank you!
