### ISSUE TITLE
rawVersion.match is not a function

### ISSUE THREAD

**Issue by TanninOne** [agc93/vortex-showcase#9]
Please see this issue: https://github.com/Nexus-Mods/Vortex/issues/7772

**Comment by agc93** [comment]
Every time I make an assumption about mod attributes, it ends up backfiring 😆 

I'll fix this up and get another release out tonight.

**Comment by agc93** [comment]
Just to close this out: [version 0.1.5 is now uploaded](https://www.nexusmods.com/site/mods/145?tab=files) which **should** fix this.
